server:
  port: 8000
  address: localhost

database:
  port: 5432
  address: postgres
  user: postgres
  password: postgres
  dbname: postgres

rabbit:
  host: rabbitmq
  port: 5672
  user: guest
  password: guest
  queue: sf